logging:
  level:
    '[com.idangdev.catalog]': TRACE

#spring datasource
spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1/book_catalog             #127.0.0.1 trus tulis port nya. habis itu nama database nya
    username: wildan                                          #best practice nya itu pake ${username.dtabase} yang disimpen di environment variable
    password: wildan
  jpa:
    database: POSTGRESQL                                      #database yang kita pakai sekarang
    hibernate:
      ddl-auto: update                                       # ddl-auto = untuk melakukan inisialisasi thd database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect      # dialect = jenis database yang kita gunakan
        jdbc:                                                 # untuk mengaktifkan loging dari sql statement nya
          batch_size: 100
        order_inserts: true
    show-sql: true                                            
      

app:
  currency: IDR
  timezone: Asia/Jakarta
  welcome-text: Hello World from Wildan, are you ready?. This is from properties?
cloud:
  api-key: ${CLOUD_KEY2}
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile:
      - development
  
server:
  port: 8003
  
app:
  welcome-text: Hello World from Wildan, are you ready?. This is development server
  
---
spring:
  config:
    activate:
      on-profile:
      - test
  
server:
  port: 8083
  
---
spring:
  config:
    activate:
      on-profile:
      - production
  
server:
  port: 80